debug = true
jwt_access_token_expires = 3600

logfile_dir = "./log_files/"
logfile_name = "app.log"
logfile_max_size = 5
logfile_max_count = 10
log_level = 12
date_format = "%y-%m-%d %h:%m:%s"
date_format2 = "%y-%m-%d_%h:%m:%s"
date_day_format = "%y-%m-%d"

jwt_secret_key = ""

[db.pg]
name = "db_test"
host = "127.0.0.1"
port = 5432
user = "root"
password = "123456"

[db.redis]
user = ""
password = ""
port = 6379
host = "127.0.0.1"

