debug = true
jwt_access_token_expires = 3600

logfile_dir = "./log_files/"
logfile_name = "app.log"
logfile_max_size = 5
logfile_max_count = 10
log_level = 12
date_format = "%y-%m-%d %h:%m:%s"
date_format2 = "%y-%m-%d_%h:%m:%s"
date_day_format = "%y-%m-%d"

jwt_secret_key = ""

db.pg.name = "db_test"
db.pg.host = "127.0.0.1"
db.pg.port = 3306
db.pg.user = ""
db.pg.password = ""

db.redis.user = ""
db.redis.password = ""
db.redis.port = 6379

